### ISSUE TITLE
Fails to build with GDAL 3.3.x (error: invalid new-expression of abstract class type 'node_gdal::GeoTransformTransformer')

### ISSUE THREAD

**Issue by sebastic** [contra/node-gdal-next#54]
As reported in [Debian Bug #992527](https://bugs.debian.org/992527):
```
In file included from ../src/node_gdal.cpp:44:
../src/gdal_coordinate_transformation.hpp: In member function 'virtual OGRCoordinateTransformation* node_gdal::GeoTransformTransformer::Clone() const':
../src/gdal_coordinate_transformation.hpp:84:45: error: invalid new-expression of abstract class type 'node_gdal::GeoTransformTransformer'
   84 |     return new GeoTransformTransformer(*this);
      |                                             ^
```

**Comment by yocontra** [comment]
@mmomtchev I see you ended up making your fork a published package - I don't have any issue deprecating this one and telling everyone to use yours in the README if you plan to continue maintaining it. The sole purpose of making this one was to fix all of the outstanding issues with the original project + keep it working on new node and gdal versions. I don't see any reason to both do this separately, so do you want to merge efforts?

**Comment by mmomtchev** [comment]
I did create this project hoping to gain better visibility since I have been out of work for more than a year now.
But no matter what will happen next with me, I am a very heavy `gdal-async` user - I am using it to slowly replace all web-facing legacy C++ code on my weather site which requires that it is fully asynchronous and `Express`-compatible in a multi-user environment. I initially used it on a small side module, but now it has been a week that it is powering a production website serving data requests with `scijs` over `Express`. So I will continue to dedicate time to this project - for at least as long as I am able to afford to pay the electricity bills.
